# Generated by Django 4.1.3 on 2022-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(default='DEFAULT', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='DEFAULT', max_length=320),
        ),
        migrations.AlterField(
            model_name='trail',
            name='maps_link',
            field=models.CharField(max_length=255),
        ),
    ]
