# Generated by Django 4.1.3 on 2022-11-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailapp', '0002_trail_difficulty_user_email_alter_trail_maps_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trail',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='lon',
        ),
    ]
